### ISSUE TITLE
REAL_TRANSPARENT emit light when generated using the custom_world plugin together with ItemsAdderBlocksInjector

### ISSUE THREAD

**Issue by MaledKhaoSan** [ItemsAdder/ItemsAdderBlocksInjector#23]
### What happened?
REAL_TRANSPARENT emit light when generated using the custom_world plugin together with ItemsAdderBlocksInjector
> At first, we attempted to create a script for generating a custom tree in Iris, where the tree consists of components like:
> - custom_wood (type: REAL_NOTE)
> - custom_leaves (type: REAL_TRANSPARENT)
> We successfully generated the tree using custom blocks from ItemsAdder along with ItemsAdderBlocksInjector.
> However, all the custom leaves (with type REAL_TRANSPARENT) emit light — even though we did not define any light source or lighting behavior in the configuration.

![Image](https://github.com/user-attachments/assets/355cc2b9-1233-4e32-93f5-50f4bbeb4b8a)

### Steps to reproduce the issue
1. Generate a world using the Iris World Generator with block injection enabled and custom leaves of type REAL_TRANSPARENT:
```powershell
/mv create custom_world -g biome:custombiome
```
2. Observe that every custom leaf block (REAL_TRANSPARENT) emits light in the generated world — despite no light being configured.

### ItemsAdder Version Info
- ItemsAdderBlocksInjector: 0.0.15
- ItemsAdder: 4.0.5
- LoneLibs: 1.0.63
- ViaVersion: 5.3.0
- PaperMC version: 1.21.1-132-ver (build b48403b)

### Problematic ItemsAdder YML Snippet (Optional)
```yaml
green_skyroot_leaves:
    display_name: green_skyroot_leaves
    resource:
      generate: false
      material: PAPER
      model_path: green_skyroot_leaves
    specific_properties:
      block:                 
        cancel_drop: false
        break_particles: BLOCK
        events_tools_whitelist:
        placed_model:
          type: REAL_TRANSPARENT
          break_particles: ITEM
        hardness: 0.1
        sound:
          break:            
            name: minecraft:block.grass.break
            volume: 1
            pitch: 0.9
          place:
            name: minecraft:block.grass.place
            volume: 1
            pitch: 0.9
          hit:
            name: minecraft:block.grass.hit
            volume: 0.25
            pitch: 0.9
          step:
            name: minecraft:block.grass.step
            volume: 0.15
            pitch: 1
```
